// codesandbox/01-getting-started/02-first-request/svelte-useRequest.en.svelte
<script>
import { useRequest } from 'alova';
import { alovaInstance } from './api';

// Use the alova instance to create a method and pass it to useRequest to send the request
const { loading, data, error } = useRequest(alovaInstance.Get('https://jsonplaceholder.typicode.com/todos/1'));
</script>

{#if $loading}
<div>Loading...</div>
{:else if $error}
<div>{ $error.message }</div>
{:else}
<span>responseData: { data }</span>
{/if}

// codesandbox/01-get-started/04-quick-start/react-useRequest.en.jsx
import { useRequest } from 'alova';
import { alovaInstance } from './api';

const App = () => {
  // Use the alova instance to create a method and pass it to useRequest to send the request
  const { loading, data, error } = useRequest(alovaInstance.Get('https://jsonplaceholder.typicode.com/todos/1'));

  if (loading) {
    return <div>Loading...</div>;
  } else if (error) {
    return <div>{error.message}</div>;
  }
  return <span>responseData: {JSON.stringify(data)}</span>;
};
export default App;
